"""GitHub integration helpers (Grok Build).

Used by automations and the agent for posting comments,
creating review summaries, etc.

All calls are expected to be preceded by a model decision
that selected the github tool/action.
"""
from __future__ import annotations

from typing import Any


def format_pr_comment(summary: dict[str, Any]) -> str:
    """Turn a structured summary into a safe PR comment body."""
    title = summary.get("title", "Mana Agent Analysis")
    body = summary.get("body", "")
    return f"**{title}**\n\n{body}\n\n_Generated by mana-agent multi-agent runtime._"


def post_pr_comment_stub(pr_number: int, comment: str) -> dict[str, str]:
    """Stub. Real impl uses PyGithub or gh CLI under model control."""
    return {"status": "stub", "pr": pr_number, "would_post": comment[:120] + "..."}
